#! /bin/sh
PIDFILE=/var/run/bmc.pid

start() {
cat<<EOF
---
                                             _
 _____ _   _ ____  ___ _   _  ____    ____  |_|     222
|_   _| | | |  _ \|_ _| \ | |/ ___|  |  _ \_ _     2   2
  | | | | | | |_) || ||  \| | |  _   | |_) || |      22 
  | | | |_| |  _ < | || |\  | |_| |  |  __/ | |     2
  |_|  \___/|_| \_\___|_| \_|\____|  |_|   |___|   22222


---
EOF

  mount /dev/mmcblk0p1 /mnt/sdcard/
  echo 3 4 1 7 > /proc/sys/kernel/printk
  /bin/bmc & _PID=$!
  echo $_PID > $PIDFILE
}

stop() {
  kill $(cat "$PIDFILE" 2> /dev/null) 2>/dev/null
  rm -f "$PIDFILE"
}

restart() {
  stop && start
}

case "$1" in
  start | stop | restart ) "$1" ;;
esac

