#! /bin/sh
PIDFILE=/var/run/bmc.pid

start() {
cat<<EOF
---

 _____ _   _ ____  ___ _   _  ____ 
|_   _| | | |  _ \|_ _| \ | |/ ___|
  | | | | | | |_) || ||  \| | |  _ 
  | | | |_| |  _ < | || |\  | |_| |
  |_|  \___/|_| \_\___|_| \_|\____|


---
EOF

  mount /dev/mmcblk0p1 /mnt/sdcard/
  echo 3 4 1 7 > /proc/sys/kernel/printk
  $(which bmc) & _PID=$!
  echo $_PID > $PIDFILE
}

stop() {
  kill $(cat "$PIDFILE" 2> /dev/null) 2>/dev/null
  rm -f "$PIDFILE"
}

restart() {
  stop && start
}

case "$1" in
  start | stop | restart ) "$1" ;;
esac

